let mongoose = require("mongoose");
let Schema = mongoose.Schema;
let AutoIncrement = require("mongoose-sequence")(mongoose);
require("mongoose-double")(mongoose);

let orderSchema = new Schema(
    {
        userId: { type: Schema.Types.ObjectId, ref: "user" },
        tempOrderId: { type: Schema.Types.ObjectId },
        product: [
            {
                productId: { type: Schema.Types.ObjectId, ref: "product" },
                name: String,
                price: Number,
                quantity: Number,
                weight: Number,
                sellerProductId: {
                    type: Schema.Types.ObjectId,
                    ref: "sellerProduct",
                },
                id: { type: Number },
                unit: String, // it can be Litre or 1 newspaper or 1 bottle
                categoryId: { type: Schema.Types.ObjectId },
                categories: [], //this shoud be array//change to categoryIds
                gst: Number,
                gstId: { type: Schema.Types.ObjectId },
                gstDesc: { type: String, lowercase: true },
                hsnCode: String,
                images: [],
                membershipPrice: { type: Number, default: 0 }, //grocery
                brandId: { type: Schema.Types.ObjectId, ref: "brands" },
                subBrandId: { type: Schema.Types.ObjectId, ref: "brands" },
                sku: { type: String, lowercase: true },
                mbSku: { type: String, lowercase: true },
                skuDescription: {
                    type: String,
                    lowercase: true,
                    default: "metro wholesale",
                },
                sellPrice: Number,
                purchasePrice: {
                    type: Number,
                    get: (value) => 0,
                    set: (value) => parseFloat(value.toFixed(2)),
                },
                recommendedAttribute: { type: String, lowercase: true },
                addmore: {},
                barCode: { type: String, lowercase: true },
                productFamilyId: { type: Schema.Types.ObjectId, default: null },
                isRefund: { type: Boolean, default: false },
                outOfStock: {
                    isOutOfStock: { type: Boolean, default: false },
                    setBy: { type: Schema.Types.ObjectId, ref: "sellers" },
                    created: Date,
                    updated: Date,
                },
            },
        ],
        address: {
            area: { type: String, lowercase: true },
            street: { type: String, lowercase: true },
            city: { type: String, lowercase: true },
            country: { type: String, lowercase: true },
            state: { type: String, lowercase: true },
            district: { type: String, lowercase: true },
            fullAddress: { type: String, lowercase: true },
            latitude: Number,
            longitude: Number,
            line1: { type: String, lowercase: true },
            line2: { type: String, lowercase: true },
            locality: { type: String, lowercase: true },
            mobileNo: Number,
            name: { type: String, lowercase: true },
            neighbourhood: { type: String, lowercase: true },
            pincode: Number,
            route: {},
            type: { type: String, lowercase: true },
            location: {},
            isDefault: { type: Boolean, default: false },
            created: Number,
            updated: Number,
        },
        grossProfit: {
            type: Number,
            default: 0,
            get: (value) => 0,
            set: (value) => parseFloat(value.toFixed(2)),
        },
        shippingAddress: [],
        billingAddress: [],
        total: Number,
        amount: {
            type: Schema.Types.Double,
        },
        status: { type: String, lowercase: true },
        state: { type: String, lowercase: true },
        quantity: Number,
        customerEmail: { type: String, lowercase: true },
        cusomerName: { type: String, lowercase: true },
        currency: { type: String, default: "INR" },
        userCancelStatus: { type: Boolean, default: false },
        userCancelDate: Number,
        razorpayOrderId: String,
        razorpayPaymentId: String,
        razorpaySignatureId: String,
        created: Number,
        updated: Number,
        subTotal: Number,
        total: Number,
        gst: Number,
        paid: { type: Boolean, default: false },
        razorpayAmount: { type: Schema.Types.Double },
        sellerId: { type: Schema.Types.ObjectId, ref: "seller" },
        cityId: { type: Schema.Types.ObjectId, ref: "cities" },
        areaId: { type: mongoose.Types.ObjectId, default: null },
        societyId: { type: Schema.Types.ObjectId, ref: "societies" },
        date: { type: Date },
        addressId: { type: Schema.Types.ObjectId },
        deliveryBoyRating: { type: Number },
        deliveryBoyComments: { type: String },
        deliveryDate: Date,
        deliveryTime: {},
        paymentMode: {
            type: String,
            default: "wallet",
        },
        deliveryCharge: {
            type: Number,
            default: 0,
            set: (value) => parseFloat(value.toFixed(2)),
        },
        isDeliveryCharge: { type: Boolean, default: false },
        paymentMode: {},
        isRefundable: { type: Boolean, default: true },
        isRefunded: { type: Boolean, default: false },
        isOrderAssigned: { type: Boolean, default: false },
        promocode: String,
        offerId: { type: Schema.Types.ObjectId, ref: "offers" },
        paidToSeller: { type: Boolean, default: false },
        otp: Number,
        transactionId: Number,
        deliveredDate: Date,
        totalSaving: String,
        paymentType: { type: String },
        codTransactionId: { type: String },
        totalSaving: String,
        couponDiscount: {
            type: Number,
            get: (value) => parseFloat(value.toFixed(2)), // Ensure two decimal places
            set: (value) => parseFloat(value.toFixed(2)),
        },
        isCancelVerifyBySeller: { type: Boolean, default: false },
        CancelVerifyDateBySeller: Date,
        paytm: {
            orderId: { type: String },
            bankName: { type: String },
            bankTxnId: { type: String },
            paymentMode: { type: String },
            status: { type: String },
            txnAmount: { type: String },
            txnDate: { type: String },
            txnId: { type: String },
            respMessage: { type: String },
            MID: { type: String },
        },
        subscriptionId: { type: Schema.Types.ObjectId, ref: "subscription" },
        platform: { type: String, lowercase: true },
        sellerInfo: {},
        isIssueRaised: { type: Boolean, default: false },
        deliveryBoyId: {
            type: Schema.Types.ObjectId,
            default: null,
            ref: "deliveryBoy",
        },
        jobId: { type: Schema.Types.ObjectId, ref: "job" },
        inTransitProducts: [
            {
                productId: { type: Schema.Types.ObjectId, ref: "product" },
                quantity: { type: Number, default: 0 },
                sellPrice: { type: Number, default: null },
                price: { type: Number, default: null },
                status: { type: String, default: "pending" },
            },
        ],
        returnProducts: [
            {
                productId: { type: Schema.Types.ObjectId, ref: "product" },
                price: Number,
                unitPrice: Number,
                quantity: Number,
                created: Date,
                updated: Date,
            },
        ],
        outOfStockProducts: [
            {
                productId: { type: Schema.Types.ObjectId, ref: "product" },
                price: Number,
                unitPrice: Number,
                quantity: Number,
                created: Date,
                updated: Date,
            },
        ],
        isCashbackOrder: { type: Boolean, default: false },
        cashbackAmount: { type: Number, default: 0 },
        isCashbackGiven: { type: Boolean, default: false },
        isReturn: { type: Boolean, default: false },
        isOutOfStock: { type: Boolean, default: false },

        errorValidation: String,
        routeId: { type: Schema.Types.ObjectId },
        posPaymentInfo: {},
        paymentSource: {},
        invoiceId: String,
        customerMessage: String,
        confirmedStateTime: Date,
        processedStateTime: Date,
        dispatchedStateTime: Date,
        deliveredStateTime: Date,
        paymentSource: {},
        source: {},
        device: {},
        easeBuzzResponse: {},
        qrLink: String,
        accessKey: String,
        rating: Number,
        previousProducts: [],
        nthOrder: { type: Number, default: 0 },
        smallCartFee: { type: Number, default: 0 },
    },
    {
        toObject: { getters: true, setters: true },
        toJSON: { getters: true, setters: true },
        runSettersOnQuery: true,
    }
);

orderSchema.plugin(AutoIncrement, { inc_field: "id", id: "orderId" });
module.exports = mongoose.model("order", orderSchema);
